# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/master/www/docs/static/schema.json
version: 2

project_name: stegsolve-rs

builds:
  - id: "stegsolve-rs"
    builder: rust
    env:
      - PKG_CONFIG_ALLOW_CROSS=1
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-pc-windows-gnu
      # - x86_64-apple-darwin
      # - aarch64-apple-darwin

nfpms:
  - ids:
      - "stegsolve-rs"
    maintainer: DawnMagnet
    description: A Rust implementation of Stegsolve for steganography analysis
    homepage: https://github.com/DawnMagnet/stegsolve-rs
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
      - apk
    overrides:
      deb:
        dependencies:
          - libxkbcommon0
          - libfontconfig1
      rpm:
        dependencies:
          - libxkbcommon
          - fontconfig
      archlinux:
        dependencies:
          - libxkbcommon
          - fontconfig
      apk:
        dependencies:
          - libxkbcommon
          - fontconfig
    bindir: /usr/bin
upx:
  - # Whether to enable it or not.
    #
    # Templates: allowed.
    enabled: true

    # Filter by build ID.
    ids:
      - "stegsolve-rs"
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best
checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
