[package]
name = "stegsolve-rs"
version = "0.2.1"
edition = "2024"
authors = ["DawnMagnet"]
description = "A Rust implementation of Stegsolve for steganography analysis"
license = "MIT"
repository = "https://github.com/DawnMagnet/stegsolve-rs"

[package.metadata.wix]
upgrade-guid = "7DCE9BB7-728C-428D-AA4E-642E7A69F52D"
path-guid = "E7B13FC9-23C3-4AF5-A5CE-850F7A010EB2"
license = false
eula = false

[lib]
name = "stegsolve_rs"
path = "src/lib.rs"

[[bin]]
name = "stegsolve-rs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# when linux build, use slint with the "backend-linuxkms" feature, which uses the KMS/DRM subsystem for rendering. This allows for better performance and compatibility with a wider range of hardware.

[target.'cfg(target_os = "linux")'.dependencies]
slint = { version = "*", default-features = false, features = [
    "std",
    "backend-winit",
    "renderer-software",
    "compat-1-2",
] }
rfd = { version = "*", default-features = false, features = ["xdg-portal"] }
fontique = { version = "0.7", features = ["fontconfig-dlopen"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
slint = { version = "*", default-features = false, features = [
    "std",
    "backend-winit",
    "renderer-software",
    "compat-1-2",
] }
rfd = "*"
[dependencies]
image = { version = "*", default-features = false, features = [
    "png",
    "jpeg",
    "gif",
    "bmp",
    "tiff",
    "webp",
] }
anyhow = "*"
arboard = "*"

[dev-dependencies]
proptest = "*"
pretty_assertions = "*"

[build-dependencies]
slint-build = "*"

[target.'cfg(windows)'.build-dependencies]
winresource = "*"

[profile.release]
strip = true      # 去除调试符号
lto = true        # 链接时优化
codegen-units = 1 # 更好的优化
opt-level = "z"   # 优先体积而非速度
panic = "abort"   # 减小panic处理代码
